# This is a basic workflow to help you get started with Actions

name: Sync Forks

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            repository: irkode/hugoDocs
            ref: master
      - name: Get upstream Changes
        run: |
          git remote add upstream https://github.com/gohugoio/hugoDocs.git
          git remote set-url --push upstream "DISSALLOWPUSH"
          git fetch upstream --prune 2>&0
          git pull
      - name: Push to fork
        run: |
          git push
