# This is a basic workflow to help you get started with Actions

name: Sync Forks

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            repository: irkode/hugoDocs
            ref: master
      - name: Add remote upstream
        run: |
          git remote add upstream https://github.com/gohugoio/hugoDocs.git
      - name: get changes
        run: |
          git fetch upstream --prune
          git pull
